#! /usr/bin/env python
# %%

from equitrain import get_args_parser
from equitrain import train

# %%

def main():

    parser = get_args_parser()

    train(parser.parse_args())

# %%
if __name__ == "__main__":
    main()
